TASK = ['find_lr', 'train', 'val'][1]
DATASET_PATH = ''
MODELS_PATH = DATASET_PATH + '_models'
CHECKPOINT_PATH = ''
RESUME = False
EPOCHS = 300
STEPS_PER_EPOCH = 1024 * 4
BATCH_SIZE = 128
ACCUMULATE = None
LR = 3e-4
DEVICES = 1
WORKERS = 0

N_COORDS = 2
N_FEATURES = 384
ARCHITECTURE = 'transformer'
N_LAYERS = 5
N_HEADS = 6
MLP_RATIO = 4
MAX_LEN = 96

DROPOUT = 0.
